#!/bin/bash


for j in `seq 1 10`

do

num=$j

for i in `seq 0 200 15000`

	do

	grep -A 4 "Excited state properties for EOMEA-CCSD transition $num/B1" hcn_$i.log | awk 'NR==4' | sed 's/.*=//' | sed 's/.*(\(.*\))/\1/' | sed 's/,/  /' > energy

        echo $i > cap

        paste cap energy >> hcn_rsq_b1_state$num.dat

	done

        done
 
